### ISSUE TITLE
handlers: ["fos_facebook.logout_handler"] a effacer

### ISSUE THREAD

**Issue by jlemale** [djepo/TemplateViergeSymfony2#10]
Ensuite un autre problemen bloque la maj des vendors (facebook encore), on a une ligne a commenter/effacer dans le config.yml
logout:
                handlers: ["fos_facebook.logout_handler"]

logout:
               #handlers: ["fos_facebook.logout_handler"]

**Comment by djepo** [comment]
Même problème que https://github.com/djepo/TemplateViergeSymfony2/issues/9 , je bosse dessus dès que possible

**Comment by djepo** [comment]
The template has been Updated to Symfony 2.2.
Let me Know if there are still problems.
