### ISSUE TITLE
Error running: composer install

### ISSUE THREAD

**Issue by iBet7o** [djepo/TemplateViergeSymfony2#11]
Show me the next message.

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>     - The requested package facebook/php-sdk could not be found in any version, there may be a typo in the package name.
>   Problem 2
>     - The requested package friendsofsymfony/facebook-bundle could not be found in any version, there may be a typo in the package name.
>   Problem 3
>     - The requested package friendsofsymfony/user-bundle could not be found in any version, there may be a typo in the package name.
>   Problem 4
>     - The requested package friendsofsymfony/user-bundle could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
> 
> Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

FOSFacebookBundle works to symfony2.1.8?

Thanks,

**Comment by djepo** [comment]
I don't have a proper internet connection for the moment, i'm waiting for my fai to repair it.
This problem is known, i will work on it asap.

**Comment by djepo** [comment]
The template has been Updated to Symfony 2.2.
Let me Know if there are still problems.
