### ISSUE TITLE
Dependencies cannot be resolved

### ISSUE THREAD

**Issue by wilfried2006** [djepo/TemplateViergeSymfony2#2]
I just follow the tutorial an i have this error when i run php composer.phar install

  "Problem 1
    - Installation request for facebook/php-sdk == 9999999-dev -> satisfiable by facebook/php-sdk dev-master.
    - facebook/php-sdk dev-master requires ext-curl \* -> no matching package found.
  Problem 2
    - facebook/php-sdk dev-master requires ext-curl \* -> no matching package found.
    - friendsofsymfony/facebook-bundle dev-master requires facebook/php-sdk dev-master -> satisfiable by facebook/php-sdk dev-master.
    - Installation request for friendsofsymfony/facebook-bundle == 9999999-dev -> satisfiable by friendsofsymfony/facebook-bundle dev-master.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
  "

**Comment by djepo** [comment]
I have other bugs in that section, but there are problems.
I will look into thoses problems, but for the moment, you can try 2.0.x version, which is stable.
Master is currently running with beta version of symfony 2.1, the problem might be here ?

Your problem with ext-curl seems to be a php configuration problem, did you enabled this extension in your php.ini ?

**Comment by wilfried2006** [comment]
It works.
Thanks

**Comment by vwasteels** [comment]
I'm still having the issue with ext-curl,

CURL is well isntalled on my WAMP
I'm using SF2.1 ... Is it a compatibility issue ? 

thanks

**Comment by djepo** [comment]
I don't use Curl, so i can't help you on that point. Maybe wilfried2006 can help you ?
