### ISSUE TITLE
v 2.0.x problem input data

### ISSUE THREAD

**Issue by wilfried2006** [djepo/TemplateViergeSymfony2#4]
Hi, i have a little problem with your v2.0.X . after folllowing all the steps  of the Readme. it works but it doesnt import data in my mysql database for a user connected with his facebook account.

**Comment by djepo** [comment]
The datas imported are stored in fos_user table.
The script imports email, username (the facebook id), lastname and firstname.
Check if this is ok.
If you test it with your own account wich have the same email, only the facebook id is added to your line in the user's table.

You can also check in the symfony's debug bar if a user is connected.

Everything works well for me.

**Comment by wilfried2006** [comment]
i deploy you template in this url http://backupyourbrain.alwaysdata.net/, i create the database and update the schema. Bu the only user registered is the one i registered from fosuserbundle. when i connect myself with my facebook accoun it doesnt work.

**Comment by djepo** [comment]
I've seen i have a typo in the 2.0's readme.
The download link is for master instead of 2.0.
Did you follow that link, or did you click on "download zip" at the top of gitHub's window (which is THE good link) ?

**Comment by wilfried2006** [comment]
I download the 2.0 zip file. I think that may be the problem is because i use sub domain name. it's a free hosting plan. don't you think so?

**Comment by wilfried2006** [comment]
Wh i coonnecct myself with q user create from the register page, the welcome page show 
Welcome wilfried2006 Logout(link).
When its with my facebook account: Home Login(link)

Another thing i saw is that when i connect with my facebook  account, it opens a popup page i remarks in url:

https://www.facebook.com/login.php?api_key=263778820386586&skip_api_login=1&display=popup&social_plugin=login_button&next=http%3A%2F%2Fwww.facebook.com%2Fdialog%2Fplugin.perms%3F_path%3Dplugin.perms%26app_id%3D263778820386586%26display%3Dpopup%26perms%3Demail%26secure%3Dfalse%26social_plugin%3Dlogin_button%26return_params%3D%257B%2522api_key%2522%253A%2522263778820386586%2522%252C%2522auto_logout_link%2522%253A%2522true%2522%252C%2522channel%2522%253A%2522http%253A%252F%252Fstatic.ak.facebook.com%252Fconnect%252Fxd_arbiter.php%253Fversion%253D9%2523cb%253Df1f72324c%2526origin%253Dhttp%255Cu00253A%255Cu00252F%255Cu00252Fbackupyourbrain.alwaysdata.net%255Cu00252Ff3eed12d48%2526domain%253Dbackupyourbrain.alwaysdata.net%2526relation%253Dparent.parent%2522%252C%2522locale%2522%253A%2522en_US%2522%252C%2522login_text%2522%253A%2522%2522%252C%2522scope%2522%253A%2522email%2522%252C%2522sdk%2522%253A%2522joey%2522%252C%2522ret%2522%253A%2522perms%2522%257D%26login_params%3D%257B%257D%26from_login%3D1%26client_id%3D263778820386586&rcount=1

it's always your api key in spite the fact i change it in the facebookparameter.ini

**Comment by djepo** [comment]
Did you clear the cache ?

**Comment by wilfried2006** [comment]
i did it many times but i have the same problem. does the 2.1 release works  ?

**Comment by djepo** [comment]
It works. That version is still currently RC1.

**Comment by inquire** [comment]
I have the same problem. It logs in in the sense that the accept app notification appears and the login button transforms into the logout, but there is no user logged in. Any ideas, what is going on?  Also, i am running on the master branch.

**Comment by djepo** [comment]
i've made an update, try that one maybe.
Every tests i've made are ok.

**Comment by inquire** [comment]
I'm on it. Will report back.

**Comment by djepo** [comment]
Try to see if [that link](https://github.com/djepo/TemplateViergeSymfony2/issues/7) can help you

**Comment by djepo** [comment]
No more information for 7 month now, I close this thread.
