### ISSUE TITLE
v 2.1 facebook problem

### ISSUE THREAD

**Issue by inquire** [djepo/TemplateViergeSymfony2#7]
Hello, 

I've installed the bundle and the problem i have is that when i login, the login button changes to logout, but no user is registered, nor is he recognized. the FOSUser form works well, but not FOSFacebook. Do you have any ideas why?

**Comment by djepo** [comment]
I really don't understand that bug, because everyting works fine.
When a user is connected via facebook, a user is created in the table (you can look into fos_user table), and the user is connected with the facebook id as username.
I will make some tests with an other facebook acount.

**Comment by inquire** [comment]
Please do if you can. So what i did was clone your repo and just add the database configuration and facebook app parameters, and although i can login from the form, when i login with facebook, it does not redirect to anything, and only the button changes from login to logout. Maybe your local repo is ahead of the github repo if you say yours works well?

**Comment by djepo** [comment]
I made another test account on facebook, and everything works fine.
Be carefull of your website's url in your facebook app parameters, for example, i have http://localhost/TemplateViergeSymfony2/ and that works.

The repo is in sync with my computer, so we have the same versions.
Try to see if firebug report you any error...

**Comment by inquire** [comment]
The problem was in my configuration of the facebook web app where i didn't add the port to my localhost. Works wonderfully. Thank you, thank you, thank you!
