### ISSUE TITLE
Changement de configuration de fos_facebook : parametre file devenu inutile

### ISSUE THREAD

**Issue by jlemale** [djepo/TemplateViergeSymfony2#9]
Merci pour le template ! J'espere que ca va marcher!!..
Lorsque j'installe les vendors ca plante au niveau de facebook car la config du bundle a un peu change : Unrecognized options "file" under "fos_facebook"

**Comment by djepo** [comment]
Oui j'ai vu ca, malheureusement je n'ai pas trop de temps pour le moment, mais dès que j'ai un moment, je bosserais dessus.

**Comment by djepo** [comment]
The template has been Updated to Symfony 2.2.
Let me Know if there are still problems.
